name = "Minesweeper"

default_targets = ["win32", "win64", "macos", "lovejs"]
build_directory = "exports"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
]

love_version = "11.5"

icon_file = "assets/logo.png"

[lovejs]
title = "Minesweeper"
